Repository Dog-Han-Developer/doggu, pull requests merged in 2021-12, with the labels that each got.

#4 Feat/3 사용자 및 Spring Security에 대한 기능을 구현한다.
  back/.gitignore
  back/build.gradle
  back/src/main/java/com/doghandeveloper/doggu/account/controller/AccountController.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/Account.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/Dog.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/Gender.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/UserAccount.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/UserRole.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/LoginRequest.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/RefreshRequest.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/SignupRequest.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/response/AccountResponse.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/response/AuthResponse.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/response/RefreshResponse.java
  back/src/main/java/com/doghandeveloper/doggu/account/repository/AccountRepository.java
  back/src/main/java/com/doghandeveloper/doggu/account/service/AccountService.java
  back/src/main/java/com/doghandeveloper/doggu/common/config/AppProperties.java
  back/src/main/java/com/doghandeveloper/doggu/common/config/OpenApiConfig.java
  back/src/main/java/com/doghandeveloper/doggu/common/config/SecurityConfig.java
  back/src/main/java/com/doghandeveloper/doggu/common/config/WebMvcConfig.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/AuthException.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/BusinessException.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/EntityException.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/ErrorCode.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/ErrorResponse.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/GlobalExceptionHandler.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/InputValueException.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/CurrentAccount.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/CustomUserDetailsService.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/LoginFilter.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/LoginSuccessHandler.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/RestAccessDeniedHandler.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/RestAuthenticationEntryPoint.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/TokenAuthenticationFilter.java
  back/src/main/java/com/doghandeveloper/doggu/common/security/TokenProvider.java
  back/src/main/java/com/doghandeveloper/doggu/common/util/RedisUtil.java
Labels: 백엔드💻, 회원👨‍👩‍👧‍👦

#8 feat/7 강아지 인증을 구현한다.
  back/src/main/java/com/doghandeveloper/doggu/account/controller/AccountController.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/DogRegistrationRequest.java
Labels: 백엔드💻, 강아지🐕

#9 feat/5 이메일로 인증코드 전송 및 확인 기능을 구현한다.
  back/build.gradle
  back/src/main/java/com/doghandeveloper/doggu/account/controller/AccountController.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/EmailAuthenticationRequest.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/response/EmailAuthenticationCodeResponse.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/response/EmailAuthenticationResponse.java
  back/src/main/java/com/doghandeveloper/doggu/common/config/EmailProperties.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/EmailSendException.java
  back/src/main/java/com/doghandeveloper/doggu/common/exception/ErrorCode.java
  back/src/main/java/com/doghandeveloper/doggu/common/util/EmailSendUtil.java
  back/src/main/resources/application.properties
Labels: 백엔드💻, 회원👨‍👩‍👧‍👦

#12 Feat/11 강아지 모델 등록(수정) API를 구현한다.
  back/src/main/java/com/doghandeveloper/doggu/account/controller/AccountController.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/Account.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/Dog.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/DogModel.java
  back/src/main/java/com/doghandeveloper/doggu/account/domain/Sex.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/DogInfoRequest.java
  back/src/main/java/com/doghandeveloper/doggu/account/dto/request/SignupRequest.java
  back/src/main/java/com/doghandeveloper/doggu/account/repository/DogRepository.java
  back/src/main/java/com/doghandeveloper/doggu/account/service/AccountService.java
Labels: 백엔드💻, 회원👨‍👩‍👧‍👦, 강아지🐕

#15 FIX security관련 설정 변경
  back/build.gradle
  back/src/main/java/com/doghandeveloper/doggu/account/controller/AccountController.java
  back/src/main/java/com/doghandeveloper/doggu/common/config/SecurityConfig.java
Labels: 백엔드💻, 회원👨‍👩‍👧‍👦, 강아지🐕

#18 Feature/fe signup
  front/signin/src/page/signup.js
  front/signin/src/page/signup.template.js
  front/signin/src/page/views/index.js
  front/signin/src/page/views/password-field.js
  front/signin/src/page/views/password-field.template.js
  front/signin/src/page/views/radio-select-field.js
  front/signin/src/page/views/radio-select-field.template.js
Labels: 프론트엔드✨, 회원👨‍👩‍👧‍👦
